### ISSUE TITLE
Error while loading jni library

### ISSUE THREAD

**Issue by constantmanish** [goldshtn/libstapsdt-jni#1]
HI @goldshtn , 
I build the jni library as per the script and tried to load this on my own program , but this throws Exception, 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/support/libstapsdt-master/libstapsdt-jni.so: /home/support/libstapsdt-master/libstapsdt-jni.so: undefined symbol: __gxx_personality_v0
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at Indexing.<clinit>(Indexing.java:4)
```

Am i doing things wrong here, i am only running jni build part ,libstapsdt-jni.so is created after building without issue, This error is seen once i try to run the java program.

**Comment by constantmanish** [comment]
```
g++ -shared -fPIC -std=c++11 -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux -I out \
    -o libstapsdt-jni.so sdt_Native.cc
```
Or,
```
gcc -shared -fPIC -std=c++11 -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux -I out \
    -o libstapsdt-jni.so sdt_Native.cc -lstdc++
```
this works fine
